# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from contract import service_pb2 as contract_dot_service__pb2


class PredictionServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.predict = channel.unary_unary(
        '/PredictionService/predict',
        request_serializer=contract_dot_service__pb2.PredictRequest.SerializeToString,
        response_deserializer=contract_dot_service__pb2.PredictResponse.FromString,
        )
    self.stream_predict = channel.stream_unary(
        '/PredictionService/stream_predict',
        request_serializer=contract_dot_service__pb2.PredictRequest.SerializeToString,
        response_deserializer=contract_dot_service__pb2.StreamPredictResponse.FromString,
        )


class PredictionServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def predict(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def stream_predict(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PredictionServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'predict': grpc.unary_unary_rpc_method_handler(
          servicer.predict,
          request_deserializer=contract_dot_service__pb2.PredictRequest.FromString,
          response_serializer=contract_dot_service__pb2.PredictResponse.SerializeToString,
      ),
      'stream_predict': grpc.stream_unary_rpc_method_handler(
          servicer.stream_predict,
          request_deserializer=contract_dot_service__pb2.PredictRequest.FromString,
          response_serializer=contract_dot_service__pb2.StreamPredictResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'PredictionService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
